import type { CiProvider } from "./recipes/types.js";

export interface CiSnippetOptions {
  provider: CiProvider;
  /** a11y-sdk version to pin the step to (rendered as vX.Y.Z). */
  version: string;
  /** Install target relative to repo root; "." for standalone. */
  scope: string;
  /** Optional URL for an R3 audit step; omitted → audit step is commented out. */
  auditUrl?: string;
}

function pinnedTag(version: string): string {
  return version.startsWith("v") ? version : `v${version}`;
}

/**
 * Emit a CI pipeline step that installs the a11y toolkit pinned to this tag,
 * runs the a11y ESLint gate over the repo, and (optionally) an axe-core audit.
 * Mirrors the devkit's `template/ci/embedded-step.yml` shape (plan §1.5).
 */
export function emitCiSnippet(opts: CiSnippetOptions): string {
  const tag = pinnedTag(opts.version);
  const scopeFlag = opts.scope && opts.scope !== "." ? ` --scope ${opts.scope}` : "";
  const auditCmd = `npx --yes a11y-sdk@${tag} audit ${opts.auditUrl ?? "http://localhost:3000"} --json`;

  if (opts.provider === "github") {
    return githubSnippet(tag, scopeFlag, auditCmd, Boolean(opts.auditUrl));
  }
  return bitbucketSnippet(tag, scopeFlag, auditCmd, Boolean(opts.auditUrl));
}

function githubSnippet(
  tag: string,
  scopeFlag: string,
  auditCmd: string,
  audit: boolean,
): string {
  const auditBlock = audit
    ? `      - name: a11y audit (axe-core)\n        run: ${auditCmd}\n`
    : `      # Optional axe-core audit against a running preview:\n      # - name: a11y audit (axe-core)\n      #   run: ${auditCmd}\n`;
  return `# .github/workflows/a11y.yml — generated by a11y-sdk ${tag}
name: a11y
on: [pull_request]
jobs:
  a11y:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install project deps
        run: npm ci
      - name: Install a11y ESLint config (pinned)
        run: npx --yes a11y-sdk@${tag} init --only lint --hook-strategy none --yes${scopeFlag}
      - name: Run a11y lint gate
        run: npx eslint . --config .a11y/config/eslint/react.cjs
${auditBlock}`;
}

function bitbucketSnippet(
  tag: string,
  scopeFlag: string,
  auditCmd: string,
  audit: boolean,
): string {
  const auditBlock = audit
    ? `          - ${auditCmd}\n`
    : `          # Optional axe-core audit against a running preview:\n          # - ${auditCmd}\n`;
  return `# bitbucket-pipelines.yml step — generated by a11y-sdk ${tag}
pipelines:
  pull-requests:
    '**':
      - step:
          name: a11y
          image: node:20
          script:
            - npm ci
            # Install a11y ESLint config pinned to the release tag
            - npx --yes a11y-sdk@${tag} init --only lint --hook-strategy none --yes${scopeFlag}
            # Adjust the framework config file (react|vue|svelte|angular) as needed
            - npx eslint . --config .a11y/config/eslint/react.cjs
${auditBlock}`;
}
